djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)

from .views import LandingPageView, SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('signup', SignUpView.as_view(), name='sign-up'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path

from .views import (
    LeadListView, LeadDetailView, LeadCreateView,
    LeadUpdateView, LeadDeleteView, AssignLeadView,
)

app_name = 'leads'

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>', LeadDetailView.as_view(), name='lead-detail'),
    path('create', LeadCreateView.as_view(), name='lead-create'),
    path('<int:pk>/update', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-lead', AssignLeadView.as_view(), name='assign-lead'),
]

leads/models.py
from django.shortcuts import reverse
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


class User(AbstractUser):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    """
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.user.username


class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey(
        "Agent", null=True, blank=True, on_delete=models.SET_NULL)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

    def __repr__(self) -> str:
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('leads:lead-detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('leads:lead-update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('leads:lead-delete', kwargs={'pk': self.pk})

    def get_assign_url(self):
        return reverse('leads:assign-lead', kwargs={'pk': self.pk})


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=20, unique=True, db_index=True)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('agents:agent-detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('agents:agent-update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('agents:agent-delete', kwargs={'slug': self.slug})

    def __str__(self) -> str:
        return self.user.username

    def __repr__(self) -> str:
        return self.user.username


def post_user_created_signal(sender, instance, created, **kwargs):
    """Created UserProfile for new user"""
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms

from .models import Lead, Agent


class LeadForm(forms.ModelForm):

    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'email',
            'phone_number',
            'agent',
            'description',
        )

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(LeadForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class AssignLeadForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none(), required=False)

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignLeadForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents

leads/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.views import generic
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from agents.mixins import OrganisorAndLoginRequiredMixin
from .models import Lead
from .forms import LeadForm, AssignLeadForm


class LeadListView(LoginRequiredMixin, generic.ListView):
    """View for displaying leads"""
    model = Lead
    template_name = 'leads/lead_list.html'
    context_object_name = 'leads'

    def get_queryset(self):
        """Filter leads, hides foreign leads"""
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user)
        return queryset


class LeadDetailView(LoginRequiredMixin, generic.DetailView):
    """View for displaying a lead"""
    model = Lead
    template_name = 'leads/lead_detail.html'
    context_object_name = 'lead'

    def get_queryset(self):
        """Filter leads, hides foreign leads"""
        user = self.request.user
        if user.is_organisor:
            queryset = Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset = Lead.objects.filter(organisation=user.agent.organisation)
            queryset = queryset.filter(agent__user=user)
        return queryset


class LeadCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    """View for creating a new lead"""
    model = Lead
    template_name = 'leads/lead_create.html'
    form_class = LeadForm
    
    def get_form_kwargs(self, **kwargs):
        """Return the keyword arguments for instantiating the form"""
        kwargs = super(LeadCreateView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs
    
    def form_valid(self, form):
        """Added organisation for a lead after creating"""
        lead = form.save(commit=False)
        lead.organisation = self.request.user.userprofile
        lead.save()
        """Sending email"""
        send_mail(
            subject="A lead has been created",
            message="Go to the site to see the new lead",
            from_email="rezov.n@mail.ru",
            recipient_list=["jayhosee@gmail.com"],
        )
        messages.success(self.request, "You have successfully created a lead!")
        return super(LeadCreateView, self).form_valid(form)
    
    def get_success_url(self):
        """Redirect after successful creation"""
        return reverse('leads:lead-list')


class LeadUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    """View for updating an existing lead"""
    model = Lead
    template_name = 'leads/lead_update.html'
    context_object_name = 'lead'
    form_class = LeadForm

    def get_form_kwargs(self, **kwargs):
        """Return the keyword arguments for instantiating the form"""
        kwargs = super(LeadUpdateView, self).get_form_kwargs(**kwargs)
        print(kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs

    def get_queryset(self):
        """Filter leads, hides foreign leads"""
        user = self.request.user
        return Lead.objects.filter(organisation=user.userprofile)

    def get_success_url(self):
        """Redirect after successful update"""
        return reverse("leads:lead-detail", kwargs={"pk": self.get_object().id})


class LeadDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    """View for deleting the selected lead"""
    model = Lead
    template_name = 'leads/lead_delete.html'
    context_object_name = 'lead'

    def get_queryset(self):
        """Filter leads, hides foreign leads"""
        user = self.request.user
        return Lead.objects.filter(organisation=user.userprofile)

    def get_success_url(self):
        """Redirect after successful deletion"""
        return reverse('leads:lead-list')


class AssignLeadView(OrganisorAndLoginRequiredMixin, generic.FormView):
    """Assign lead with an agent"""
    model = Lead
    template_name = "leads/lead_assign.html"
    form_class = AssignLeadForm

    def get_form_kwargs(self, **kwargs):
        """Return the keyword arguments for instantiating the form"""
        kwargs = super(AssignLeadView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs
        
    def get_success_url(self):
        """Redirect after successful assigning"""
        return reverse("leads:lead-list")

    def form_valid(self, form):
        """Save assign lead-agent in db"""
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignLeadView, self).form_valid(form)

leads/templates/leads/assign_lead.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'leads:lead-list' %}">Go back to leads</a>
    <hr />
    <h1>Assign a lead to this agent</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Assign</button>
    </form>
{% endblock content %}

leads/templates/leads/lead_assign.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    
    <div class="py-5 border-b border-gray-200">
        <a class="text-gray-800 hover:text-blue-500" href="{% url 'leads:lead-list' %}">
        Go back to leads
        </a>
    </div>
    
    <h1 class="mt-3 text-2xl text-gray-800">Assign a lead to agent</h1>
    
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="mt-2 w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Assign</button>
    </form>

</div>

{% endblock content %}

leads/templates/leads/lead_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    
    <div class="py-5 border-b border-gray-200">
        <a class="text-gray-800 hover:text-blue-500" href="{% url 'leads:lead-list' %}">
        Go back to leads
        </a>
    </div>
    
    <h1 class="mt-3 text-2xl text-gray-800">Create a new lead</h1>
        
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="mb-10 mt-2 w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Create
        </button>
    </form>

</div>

{% endblock content %}

leads/templates/leads/lead_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{{ lead.get_update_url }}">
        Go back to {{ lead.first_name }} {{ lead.last_name }}
        </a>
    </div>
    
    <h1 class="mt-3 text-2xl text-gray-800">Are you sure you want to delete this lead?</h1>
    
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md">Delete</button>
    </form>

</div>

{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-2/4 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6">
                <div class="w-full py-3 flex justify-between">
                    <div>
                        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                            {{ lead.first_name }} {{ lead.last_name }}
                        </h1>
                    </div>
                    
                    <div class="mt-5 ">
                        <a class="text-gray-800 hover:text-blue-500" href="{% url 'leads:lead-list' %}">
                            Go back to leads
                        </a>
                    </div>
                </div>
                
                <div class="flex mb-4">
                    <a href="{{ lead.get_absolute_url }}" class="flex-grow text-indigo-500 text-center border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Overview
                    </a>
                    {% if request.user.is_organisor%}
                    <a href="{{ lead.get_update_url }}" class="flex-grow text-center border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>
                    {% endif %}
                </div>

                <p class="leading-relaxed mb-4">{{ lead.description }}</p>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">First Name</span>
                    <span class="ml-auto text-gray-900">{{ lead.first_name }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Last Name</span>
                    <span class="ml-auto text-gray-900">{{ lead.last_name }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Age</span>
                    <span class="ml-auto text-gray-900">{{ lead.age }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900">{{ lead.email }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Phone Number</span>
                    <span class="ml-auto text-gray-900">{{ lead.phone_number }}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-300 py-2">
                    <span class="text-gray-500">Agent</span>
                    <span class="ml-auto text-gray-900">{{ lead.agent }}</span>
                </div>
            </div>
        </div>
    </div>
  </section>
  
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Leads</h1>
            </div>
            {% if request.user.is_organisor %}
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:lead-create' %}">
                    Create a new lead
                </a>
            </div>
            {% endif %}
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            First Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Last Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Age
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Cell Phone Number
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Description
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            {% if not request.user.is_agent %}
                            Assigning
                            {% endif %}
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for lead in leads %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-700">
                                    {{ lead.first_name }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-700">
                                    {{ lead.last_name }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.age }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.email }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.phone_number }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ lead.description|truncatewords:3 }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {% if not request.user.is_agent %}
                                    {% if lead.agent %}
                                         <a class="text-green-600 hover:text-blue-500" href="{{ lead.get_assign_url }}">Assigned</a>
                                    {% else %}
                                        <a class="text-red-500 hover:text-blue-500" href="{{ lead.get_assign_url }}">Assign</a>
                                    {% endif %}
                                    {% endif %}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{{ lead.get_absolute_url }}" class="text-indigo-600 hover:text-indigo-900">
                                        Overview
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-2/4 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6">
                <div class="w-full py-3 flex justify-between">
                    <div>
                        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                            {{ lead.first_name }} {{ lead.last_name }}
                        </h1>
                    </div>
                    
                    <div class="mt-5 ">
                        <a class="text-gray-800 hover:text-blue-500" href="{% url 'leads:lead-list' %}">
                            Go back to leads
                        </a>
                    </div>
                </div>
                
                <div class="flex mb-4">
                    <a href="{{ lead.get_absolute_url }}" class="flex-grow text-center border-b-2 border-gray-300 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a href="{{ lead.get_update_url }}" class="flex-grow text-indigo-500 text-center border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>

                <form form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="w-1/3 text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
                </form>
                <div class="mt-5 py-5 border-t border-gray-200">
                    <a href="{{ lead.get_delete_url }}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}