agents/urls.py
from django.urls import path

from .views import (
    AgentListView, AgentDetailView, AgentCreateView, AgentUpdateView, AgentDeleteView
)

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create', AgentCreateView.as_view(), name='agent-create'),
    path('<slug:slug>', AgentDetailView.as_view(), name='agent-detail'),
    path('<slug:slug>/update', AgentUpdateView.as_view(), name='agent-update'),
    path('<slug:slug>/delete', AgentDeleteView.as_view(), name='agent-delete'),
]

djcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)

from .views import LandingPageView, SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('signup', SignUpView.as_view(), name='sign-up'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

agents/forms.py
from django import forms
from leads.models import User


class AgentForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
        )

agents/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.urls import reverse
from django.views import generic

from leads.models import Agent
from .forms import AgentForm
from .mixins import OrganisorAndLoginRequiredMixin


class AgentListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    """View for displaying agents"""
    model = Agent
    template_name = 'agents/agent_list.html'
    context_object_name = 'agents'

    def get_queryset(self):
        """Filter agents, hides foreign agents"""
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentDetailView(generic.DetailView):
    """View for displaying an agent"""
    model = Agent
    template_name = 'agents/agent_detail.html'
    context_object_name = 'agent'

    def get_queryset(self):
        """Filter agents, hides foreign agents"""
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)


class AgentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    """View for creating a new agent"""
    model = Agent
    template_name = 'agents/agent_create.html'
    form_class = AgentForm

    def form_valid(self, form):
        """Invite agent to CRM and sending email him"""
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.set_password('1234')
        user.save()
        Agent.objects.create(
            user=user,
            slug=user.username,
            organisation=self.request.user.userprofile
        )
        send_mail(
            subject='You are invited to be an agent',
            message='You were added as an agent on CRM. Please come login to start working',
            from_email='admin@test.com',
            recipient_list=[user.email],
        )
        messages.success(self.request, "You have successfully created an agent!")
        return super(AgentCreateView, self).form_valid(form)

    def get_success_url(self):
        """Redirect after successful creation"""
        return reverse('agents:agent-list')


class AgentUpdateView(generic.UpdateView):
    """View for updating an agent"""
    model = Agent
    template_name = 'agents/agent_update.html'
    form_class = AgentForm
    context_object_name = 'agent'

    def get_queryset(self):
        """Filter agents, hides foreign agents"""
        user = self.request.user
        return Agent.objects.filter(organisation=user.userprofile)

    def get_success_url(self):
        """Redirect after successful update"""
        return reverse("agents:agent-detail", kwargs={"slug": self.get_object().user.username})


class AgentDeleteView(generic.DeleteView):
    """View for deleting the selected agent"""
    model = Agent
    template_name = 'agents/agent_delete.html'
    context_object_name = 'agent'

    def get_queryset(self):
        """Filter agents, hides foreign agents"""
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

    def get_success_url(self):
        """Redirect after successful deletion"""
        return reverse('agents:agent-list')

agents/templates/agents/agent_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block title %}
    Agent creation
{% endblock title %}

{% block content %}

<div class="max-w-lg mx-auto">
    
    <div class="py-5 border-b border-gray-200">
        <a class="text-gray-800 hover:text-blue-500" href="{% url 'agents:agent-list' %}">
        Go back to agents
        </a>
    </div>
    
    <h1 class="mt-3 text-2xl text-gray-800">Create a new agent</h1>
        
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="mt-2 w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Create
        </button>
    </form>

</div>

{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{{ agent.get_update_url }}">
            {% if agent.user.first_name and agent.user.last_name %}
                Go back to {{ agent.user.first_name }} {{ agent.user.last_name }}
            {% else %}
                Go back to {{ agent.user.username }}
            {% endif %}
        </a>
    </div>
    
    <h1 class="mt-3 text-2xl text-gray-800">Are you sure you want to delete this agent?</h1>
    
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md">Delete</button>
    </form>

</div>

{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-2/4 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6">
                <div class="w-full py-3 flex justify-between">
                    <div>
                        <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
                        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                            {{ agent.user.username }}
                        </h1>
                    </div>
                    
                    <div class="mt-5 ">
                        <a class="text-gray-800 hover:text-blue-500" href="{% url 'agents:agent-list' %}">
                            Go back to agents
                        </a>
                    </div>
                </div>

                <div class="flex mb-4">
                    <a href="{{ agent.get_absolute_url }}" class="flex-grow text-indigo-500 text-center border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a href="{{ agent.get_update_url }}" class="flex-grow text-center border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>

                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">First Name</span>
                    <span class="ml-auto text-gray-900">{{ agent.user.first_name }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Last Name</span>
                    <span class="ml-auto text-gray-900">{{ agent.user.last_name }}</span>
                </div>
                <div class="flex border-t border-gray-300 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900">{{ agent.user.email }}</span>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-700 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-gray-800">Agents</h1>
                </div>
                <div>
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent-create' %}">Create a new agent</a>
                </div>
            </div>

            <div class="flex flex-col w-full">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                First name
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Last name
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Username
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Email
                                </th>
                                <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for agent in agents %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-700">
                                        {% if agent.user.first_name %}
                                        {{ agent.user.first_name }}
                                        {% else %}
                                        -
                                        {% endif %}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-700">
                                        {% if agent.user.last_name %}
                                        {{ agent.user.last_name }}
                                        {% else %}
                                        -
                                        {% endif %}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ agent.user.username }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {% if agent.user.email %}
                                        {{ agent.user.email }}
                                        {% else %}
                                        -
                                        {% endif %}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{{ agent.get_absolute_url }}" class="text-indigo-600 hover:text-indigo-900">
                                            Overview
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
            </div>

        </div>
      </section>
{% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-2/4 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6">
                <div class="w-full py-3 flex justify-between">
                    <div>
                        <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
                        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                            {{ agent.user.username }}
                        </h1>
                    </div>
                    
                    <div class="mt-5 ">
                        <a class="text-gray-800 hover:text-blue-500" href="{% url 'agents:agent-list' %}">
                            Go back to agents
                        </a>
                    </div>
                </div>

                <div class="flex mb-4">
                    <a href="{{ agent.get_absolute_url }}" class="flex-grow text-center border-b-2 border-gray-300 py-2 text-lg px-1">
                        Overview
                    </a>
                    <a href="{{ agent.get_update_url }}" class="flex-grow text-indigo-500 text-center border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>

                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="w-1/3 text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
                </form>
                
                <div class="mt-5 py-5 border-t border-gray-200">
                    <a href="{{ agent.get_delete_url }}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}